[project]
name = "agent-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.40.30",
    "botocore>=1.40.30",
    "fastapi>=0.116.1",
    "mcp>=1.14.0",
    "uvicorn>=0.35.0",
]
